# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Expose port if needed (not necessary for stdio based MCP server)

# Command to run the MCP server
CMD ["npm", "start"]
